---
title: "Map_Prices_by_Month_City"
author: "Zach"
date: "11/11/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Making Map with averages by Month and City with a Month Selecting Slider
```{r}
library (dplyr)
library(leaflet)
library(shiny)
library(DT)
library(leaflet)
library(dplyr)
library(tidyverse)
library(readr)
```


First Creating a Data Set to Use
```{r}
 Ultimate_averages_by_month <- Final_Ultimate_Table %>%
     group_by(`City`, `State`, `Month`) %>%
     summarise(Average_Min_Price = mean(`Minimum Ticket Price`))

Ultimate_averages_by_month_longlat <- left_join(Ultimate_averages_by_month, City_Long_Lat, by = c("City", "State"))
```

Colors
```{r}
Color <- function(Ultimate_with_averages) { 
  sapply(Ultimate_with_averages$Average_Min_Price, 
         function(Average_Min_Price) {
           if (Average_Min_Price <= 30)       {"green"} 
           else if (Average_Min_Price <= 60)  {"blue"}
           else if (Average_Min_Price <= 90)  {"orange"} 
           else if (Average_Min_Price <= 120) {"red"} 
           else {"black"}})}

icons <- awesomeIcons( icon = 'ticket-outline', iconColor = 'blue', library = 'ion', markerColor = Color(Ultimate_with_averages))
```

Selector and Map
```{r}
fluidPage(
                               selectInput(inputId = "Selector",
                                           label = "Select Month",
                                           choices = c("Please Select:",
                                                       "January",
                                                       "February",
                                                       "March",
                                                       "April",
                                                       "May",
                                                       "June",
                                                       "July",
                                                       "August",
                                                       "September",
                                                       "October",
                                                       "November",
                                                       "December" ),
                                           selected = "Please Select:"))


```


```{r}
leaflet (Ultimate_averages_by_month_longlat)
  
    Color <- function(Ultimate_averages_by_month_longlat) 
      sapply(Ultimate_averages_by_month_longlat$Average_Min_Price, 
             function(Average_Min_Price) {
               if (Average_Min_Price <= 30)       {"green"} 
               else if (Average_Min_Price <= 60)  {"blue"}
               else if (Average_Min_Price <= 90)  {"orange"} 
               else if (Average_Min_Price <= 120) {"red"} 
               else {"black"})
    
    icons <- awesomeIcons( icon = 'ticket-outline', library = 'ion', markerColor = Color(Ultimate_averages_by_month_longlat))
    leaflet(Ultimate_averages_by_month_longlat) %>%
      addTiles() %>%
      setView(lng = -98, lat = 40, zoom = 4)%>%
      addAwesomeMarkers(~Longitude,
                        ~Latitude, 
                        icon=icons, 
                        popup = ~paste("<p><b>", Ultimate_averages_by_month_longlat$City, "</b></p>",
                                       "<p>", "Average Ticket Price:", 
                                       prefix = "$",
                                       format(Ultimate_averages_by_month_longlat$Average_Min_Price, digits = 4), "</p>"), 
                        label = ~as.character(City)) %>%
      addLegend(position ="bottomright", 
                colors = c("#00CD00", "#00B2EE", "#FFA500", "#CD2626", "#000000"),
                opacity = 1,
                labels = c("<$30", "$30-60", "$60-90", "$90-120", "$120<"),
                title = "Average Prices", 
                labFormat = labelFormat(prefix = "$")
      )

    

    
    
       
Ultimate_averages_by_month_longlat %>% 
         filter(Ultimate_averages_by_month_longlat$Month.January == input$January) %>% 
         filter(Ultimate_averages_by_month_longlat$Month.February == input$February) %>% 
         filter(var_three == input$Marc
                
                
                
                
                

```

