---
title: "Ticket Prices by City Map"
author: "ECB"
date: "11/4/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Making a map of ticket prices by city

#Making the Map
```{r}
library(dplyr)
```
##Making the data useable

```{r}
Ultimate_with_averages <- Ultimate_Table %>%
  group_by(`City`, `State`) %>%
  summarise(Average_Min_Price = mean(`Minimum Ticket Price`))

Ultimate_Table <- left_join (Final_Ultimate_Table, Ultimate_with_averages, by = c("City","State"))

Ultimate_with_averages <- left_join(Ultimate_with_averages, City_Long_Lat, by = c("City", "State"))

```

#Making the colors
```{r}
Color <- function(Ultimate_with_averages) { 
  sapply(Ultimate_with_averages$Average_Min_Price, 
         function(Average_Min_Price) {
           if (Average_Min_Price <= 30)       {"green"} 
           else if (Average_Min_Price <= 60)  {"blue"}
           else if (Average_Min_Price <= 90)  {"orange"} 
           else if (Average_Min_Price <= 120) {"red"} 
           else {"black"}})}

icons <- awesomeIcons( icon = 'ticket-outline', library = 'ion', markerColor = Color(Ultimate_with_averages))
```

##Making the map


```{r}
library(leaflet)
leaflet(Ultimate_with_averages) %>%
  addTiles() %>%
  setView(lng = -98, lat = 40, zoom = 4)%>%
  addAwesomeMarkers(~Longitude,
                    ~Latitude, 
                    icon=icons, 
                    popup = ~paste("<p><b>", Ultimate_with_averages$City, "</b></p>",
                                   "<p>", "Average Ticket Price:", prefix = "$", Ultimate_with_averages$Average_Min_Price, "</p>",
                                   "<p><small>", "*Cities with multiple markers and prices have multiple venues", "</small></p>"), 
                    label = ~as.character(City)) %>%
  addLegend(position ="bottomright", 
            colors = c("#00CD00", "#00B2EE", "#FFA500", "#CD2626", "#000000"),
            opacity = 0.5,
            labels = c("<$30", "$30-60", "$60-90", "$90-120", "$120<"),
            title = "Average Prices", 
            labFormat = labelFormat(prefix = "$")
            )

```

