
title: "Ticket Vendor Comparison"
author: "ECB"
date: "10/30/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Cleaning Combined_Clean_Data to just have ticket vendors and mean price

```{r}
library(dplyr)
library(tidyverse)

ticket_vendor_comparison <- Combined_Clean_Data %>%
  group_by(`Ticket Vendor`) %>%
  summarise(average_min_price = mean(`Minimum Ticket Price`))

```

#Removing "Venue" and "Official Artist Website"

```{r}
tv_comp_clean <- ticket_vendor_comparison %>%
  slice(-c(2, 3, 4, 5, 8, 9, 10, 12, 13, 14, 16, 18, 20, 
           21, 23))
```

#Ordering/sorting data 

```{r}
tv_comp_sorted <- arrange(tv_comp_clean, average_min_price)
tv_comp_ordered <- mutate( tv_comp_sorted, 
                       'Ticket Vendor' = factor(`Ticket Vendor`, levels = `Ticket Vendor`, ordered = TRUE)
                     )
```

Fixing colnames (y axis title)

```{r}
colnames(tv_comp_ordered) <- c("Ticket Vendor","Average Minimum Price")
```

#Making a plot!

```{r}
ggplot(tv_comp_ordered, aes(`Ticket Vendor`, `Average Minimum Price`, fill = `Ticket Vendor`)) + 
     geom_bar(stat = 'identity') + 
     theme(axis.text.x = element_text(angle = 60, hjust = 1),legend.position = "none")
```


```{r}

```


