---
title: "Marcie and Julia Graphs"
author: "Marcie"
date: "11/4/2024"
output: html_document
---

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

##Generating Graph comparing cost of living and minimum ticket price (trendline)



```{r}

Usable_COL_Ticket_Data <- Final_Ticket_Data_COL[-1 * c(1390, 1464, 1465, 1466, 1467, 1902, 1907, 1908, 1909, 2046),]
View(Usable_COL_Ticket_Data)
write.csv(Usable_COL_Ticket_Data, file = "Usable_COL_Ticket_Data.csv")
```

```{r}

library(ggplot2)
ggplot(Usable_COL_Ticket_Data, aes(Cost_of_Living_Index, Minimum_Ticket_Price, color = City)) + geom_point() +ylim(0,275)
```


```{r}

library(shiny)
library(ggplot2)
runApp(shinyApp(
  ui = fluidPage(
    plotOutput("plot", click = "click", brush = "brush")
  ),
  server = function(input, output, session) {
    output$plot <- renderPlot({
      ggplot(Ultimate_Table, aes(`Cost of Living Index`, `Minimum Ticket Price`, color= City)) + geom_point()
    })
    output$table <- renderDataTable({brushedPoints(Ultimate_Table, input$plot_brush, xvar = `Cost of Living Index`, yvar = `Minimum Ticket Price`)}) 
    observeEvent(input$click, {
      cat("clicked\n")
    })
    observeEvent(input$brush, {
      cat("brushed\n")
    })}))

```

